spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    ssl:
      enabled: false

    # START 连接超时 重试配置
    connection-timeout: 1s        # 设置MQ的连接超时时间
    template:
      retry:
        enabled: true             # 开启超时重试机制
        initial-interval: 1000ms  # 失败后的初始等待时间
        multiplier: 1             # 失败后下次的等待时间倍数， 下次等待时长 = initial-interval * multiplier
        max-attempts: 3           # 最大重试次数
    # END   连接超时 重试配置

    publisher-confirm-type: correlated # 开启【发布确认】，并设置确认类型为 correlated(MQ 异步回调方式返回回执消息)
    publisher-returns: true            # 开启【发布返回】，并设置返回类型为 true(MQ 异步回调方式返回回执消息)