spring:
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web

  sleuth:
    sampler:
      probability: 1.0

logging:
  level:
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.sleuth: debug